### ISSUE TITLE
Compatible NEOS version wrong & package requirements missing

### ISSUE THREAD

**Issue by samsauter** [punktDe/form-persistence#11]
Hi there,

I really liked the idea of your package and wanted to try it out. Unfortunately, the requirements in the composer.json are wrong. I'm using NEOS 4.3.x.

**[composer.json](https://github.com/punktDe/form-persistence/blob/master/composer.json)**
```
{
    …
    "require": {
        "neos/neos": "^4.0 || ^5.0 || ^7.0",
        "neos/form": "*",
        "neos/fusion": "*",
        "league/csv":"^9.0"
    },
    …
}
```

The composer.json suggests that the package is working with NEOS v4. Which it does not because it utilizes prototypes like `Neos.Fusion:Fragment`. This prototype was introduced in 5.1 - if I checked the docs correctly (:
The requirement for`neos/fusion-form` is also not stated.

Furthermore, when trying to open the backend module, the following error is thrown:
`Relative file inclusions are only possible if a context path and filename has been passed as second argument to parse()`

By removing / commenting out the line `include: **/*.fusion` in [Root.fusion](https://github.com/punktDe/form-persistence/blob/master/Resources/Private/Fusion/Root.fusion) I can open the backend module but then I run into the issues with the prototypes.

Maybe you're package is not meant to be used with older NEOS versions - which is totally fine (I'll have to update soon, anyway). But then you could make it clear in the readme or the composer file which version to use.

I hope I can try the package in some newer version. Thanks for your effort, looks really promising!

**Comment by samsauter** [comment]
Update: I just downloaded the source and try to fix it for NEOS 4.x. I think it won't be much, anyways. I'll keep you posted.

**Comment by daniellienert** [comment]
Hey @samsauter, thanks for evaluating the package and sorry fo the inconvenience. I removed Neos 4 from the compatibility list, but sadly that does not prevent composer from installing an older - not compatible version of the package.

**Comment by samsauter** [comment]
Hi @daniellienert, thanks for getting back to me!
I got it working in my installation except for the Define Export Definitions Feature. Which is very cool :) but I don't need it right now, so this is fine in my case.
